//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace labWebAPIAngular.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Purchase_Buy_Product
    {
        public int purchase_id { get; set; }
        public int product_id { get; set; }
        public double quantity { get; set; }
        public string unit { get; set; }
        public double price { get; set; }
    
        public virtual BuyProduct BuyProduct { get; set; }
        public virtual Purchase Purchase { get; set; }
    }
}
