//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace labWebAPIAngular.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sale_Sell_Product
    {
        public int sale_id { get; set; }
        public int sell_product_id { get; set; }
        public int quantity { get; set; }
        public string unit { get; set; }
        public double price { get; set; }
    
        public virtual Sale Sale { get; set; }
        public virtual SellProduct SellProduct { get; set; }
    }
}
