//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace labWebAPIAngular.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sale
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sale()
        {
            this.Sale_Sell_Product = new HashSet<Sale_Sell_Product>();
        }
    
        public int id { get; set; }
        public int customer_id { get; set; }
        public System.DateTime added_on_date { get; set; }
        public Nullable<System.DateTime> modified_on_date { get; set; }
        public Nullable<double> total_price { get; set; }
        public Nullable<System.DateTime> completed_on_date { get; set; }
        public Nullable<System.DateTime> paid_on_date { get; set; }
    
        public virtual Customer Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sale_Sell_Product> Sale_Sell_Product { get; set; }
    }
}
